name: RuboCop Auto-correct

on: [push, pull_request]

jobs:
  rubocop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7 # Replace with your Ruby version

    - name: Install dependencies
      run: |
        gem install rubocop

    - name: Run RuboCop with auto-correct
      run: rubocop --auto-correct
