databases:
  - name: my-blog
    databaseName: my-blog
    user: my-blog

services:
  - type: web
    name: my-blog
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-blog
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false