version: 1
services:
  - name: web
    type: web
    env: ruby
    buildCommand: bundle exec rails s
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
  - name: redis
    type: redis
    plan: free
    maxmemoryPolicy: noeviction
